# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Pods for WeatherApp

  target 'WeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
